import 'package:flutter/material.dart';
import 'package:pubg_gun_info/gun_screen/gun_info.dart';

class ArScreen extends StatelessWidget {
  const ArScreen({super.key});

  @override
  Widget build(BuildContext context) {
    TextStyle textStyle = TextStyle(
      color: Colors.white,
      fontSize: 15.0,
      fontWeight: FontWeight.w700,
    );

    // 총기 리스트를 정의합니다.
    final List<Map<String, dynamic>> gunList = [
      {
        'type': 'ar',
        'description':
            '점사만 지원하는 AR이다. 기본 데미지가 43으로 5탄 AR중 가장 높은데다 탄속도 910m/s로 가장 빠르고, 타 5탄 AR과 다르게 기본 헤드샷 데미지도 101이라 노뚝 헤드 한방이 가능하다. 심지어 연사력도 800RPM으로 가장 높아서, 평균 DPS값이 5.56mm AR중 유일하게 500대라서 5.56mm 탄약을 사용하는 모든 AR중 최고급의 화력을 제공한다.[14] 거기에 탄속도 빠른데다 단발 데미지도 높고, 뮤턴트와 마찬가지로 예광탄도 적용되어 있어서 DMR로 사용하기도 좋다. 무엇보다 8배율과 15배율이 장착이 가능해서 장거리 사격까지 제한적으로 가능한 이론상 만능 소총이다.',
        'name': 'M16A4',
        'ammunition': '5.56mm',
        'ammunition_image': 'asset/img/5탄.png',
        'image': 'asset/img/m16a4.png',
        'magazine': '30',
        'shotmode': '단발/3점사',
        'damage': '43',
        'muzzleVelocity': '900m/s',
        'stoppingPower': '8000',
        'ttk': '0.3s',
        'dps': '573',
        'reloadTime': '2.2s',
        'spawnArea': '모든맵',
        'attachments': [
          'asset/img/레드도트.png',
          'asset/img/홀로그램.png',
          'asset/img/2배율.png',
          'asset/img/3배율.png',
          'asset/img/4배율.png',
          'asset/img/6배율.png',
          'asset/img/8배율.png',
          'asset/img/15배율.png',
          'asset/img/캔티드.png',
          'asset/img/열화상4배율.png',
          'asset/img/ar소음기.png',
          'asset/img/ar소염기.png',
          'asset/img/ar보정기.png',
          'asset/img/ar퀴드로우.png',
          'asset/img/ar대탄.png',
          'asset/img/ar대퀵.png',
          'asset/img/개머리판.png',
          'asset/img/중량개머리판.png',
        ],
        'attachments_name': [
          '레드 도트 사이트',
          '홀로그램 조준기',
          '2배율 스코프',
          '3배율 스코프',
          '4배율 스코프',
          '6배율 스코프',
          '8배율 스코프',
          '15배율 스코프',
          '캔티드 사이트',
          '4배율 열화상 스코프',
          '소음기(AR,DMR,S12K)',
          '소염기(AR,DMR,S12K)',
          '보정기(AR,DMR,S12K)',
          '퀵드로우 탄창(AR,DMR,S12K)',
          '대용량 탄창(AR,DMR,S12K)',
          '대용량 퀵드로우 탄창(AR,DMR,S12K)',
          '전술 개머리판',
          '중량형 개머리판(SMG,AR,M249)'
        ],
      },
      {
        'type': 'ar',
        'description':
            'M416은 PUBG에서 유명한 독일제 카빈소총인 H&K HK416을 모티브로 하며, 뛰어난 안정성과 근거리 및 중거리 전투에 적합하다. 다양한 부착물을 장착할 수 있어 확장성이 뛰어나지만, 부착물에 의존도가 높고, 피해량과 화력 면에서는 일부 AR에 비해 약한 편이다. 그러나 안정성과 조준속도 등의 장점으로 초보자들에게 인기가 있으며, 베릴과 같은 다른 AR에 비해 더 나은 선택이 될 수 있다.',
        'name': 'M416',
        'image': 'asset/img/m416.png',
        'ammunition': '5.56mm',
        'ammunition_image': 'asset/img/5탄.png',
        'magazine': '30',
        'shotmode': '단발/연사',
        'damage': '40',
        'muzzleVelocity': '880m/s',
        'stoppingPower': '3500',
        'ttk': '0.428s',
        'dps': '466.67',
        'reloadTime': '3.2s',
        'spawnArea': '모든맵',
        'attachments': [
          'asset/img/레드도트.png',
          'asset/img/홀로그램.png',
          'asset/img/2배율.png',
          'asset/img/3배율.png',
          'asset/img/4배율.png',
          'asset/img/6배율.png',
          'asset/img/8배율.png',
          'asset/img/15배율.png',
          'asset/img/캔티드.png',
          'asset/img/열화상4배율.png',
          'asset/img/ar소음기.png',
          'asset/img/ar소염기.png',
          'asset/img/ar보정기.png',
          'asset/img/ar퀴드로우.png',
          'asset/img/ar대탄.png',
          'asset/img/ar대퀵.png',
          'asset/img/개머리판.png',
          'asset/img/중량개머리판.png',
          'asset/img/앵글.png',
          'asset/img/수직.png',
          'asset/img/하프.png',
          'asset/img/라이트.png',
          'asset/img/엄지.png',
          'asset/img/레이저사이트.png',
        ],
        'attachments_name': [
          '레드 도트 사이트',
          '홀로그램 조준기',
          '2배율 스코프',
          '3배율 스코프',
          '4배율 스코프',
          '6배율 스코프',
          '8배율 스코프',
          '15배율 스코프',
          '캔티드 사이트',
          '4배율 열화상 스코프',
          '소음기(AR,DMR,S12K)',
          '소염기(AR,DMR,S12K)',
          '보정기(AR,DMR,S12K)',
          '퀵드로우 탄창(AR,DMR,S12K)',
          '대용량 탄창(AR,DMR,S12K)',
          '대용량 퀵드로우 탄창(AR,DMR,S12K)',
          '전술 개머리판',
          '중량형 개머리판(SMG,AR,M249)',
          '앵글 손잡이',
          '수직 손잡이',
          '하프 그립',
          '라이트 그립',
          '엄지 그립',
          '레이저 사이트'
        ],
      },
      {
        'type': 'ar',
        'description': '벨기에의 FN SCAR-L은 다른 5.56mm AR에 비해 연사속도가 낮지만 명중률과 안정성이 뛰어나 중장거리에서 우수한 성능을 발휘한다. M416보다 반동이 적어 초보자도 쉽게 사용할 수 있으며, 다양한 부착물을 장착하여 후반 잠재력을 높일 수 있다. 그러나 DPS가 낮아 근거리에서의 화력 싸움에서 밀리는 경향이 있으며, 좁은 시야와 반동 너프로 인해 연사 대결에서 우위를 점하기 어려워졌다.',
        'name': 'SCAR-L',
        'image': 'asset/img/scar-l.png',
        'ammunition': '5.56mm',
        'ammunition_image': 'asset/img/5탄.png',
        'magazine': '30',
        'shotmode': '단발/연사',
        'damage': '42',
        'muzzleVelocity': '870m/s',
        'stoppingPower': '9000',
        'ttk': '0.48s',
        'dps': '437.5',
        'reloadTime': '3.2s',
        'spawnArea': '모든맵',
        'attachments': [
          'asset/img/레드도트.png',
          'asset/img/홀로그램.png',
          'asset/img/2배율.png',
          'asset/img/3배율.png',
          'asset/img/4배율.png',
          'asset/img/6배율.png',
          'asset/img/캔티드.png',
          'asset/img/열화상4배율.png',
          'asset/img/ar소음기.png',
          'asset/img/ar소염기.png',
          'asset/img/ar보정기.png',
          'asset/img/ar퀴드로우.png',
          'asset/img/ar대탄.png',
          'asset/img/ar대퀵.png',
          'asset/img/앵글.png',
          'asset/img/수직.png',
          'asset/img/하프.png',
          'asset/img/라이트.png',
          'asset/img/엄지.png',
          'asset/img/레이저사이트.png',
        ],
        'attachments_name': [
          '레드 도트 사이트',
          '홀로그램 조준기',
          '2배율 스코프',
          '3배율 스코프',
          '4배율 스코프',
          '6배율 스코프',
          '캔티드 사이트',
          '4배율 열화상 스코프',
          '소음기(AR,DMR,S12K)',
          '소염기(AR,DMR,S12K)',
          '보정기(AR,DMR,S12K)',
          '퀵드로우 탄창(AR,DMR,S12K)',
          '대용량 탄창(AR,DMR,S12K)',
          '대용량 퀵드로우 탄창(AR,DMR,S12K)',
          '앵글 손잡이',
          '수직 손잡이',
          '하프 그립',
          '라이트 그립',
          '엄지 그립',
          '레이저 사이트'
        ],
      },
      {
        'type': 'ar',
        'description': 'H&K G36C는 700 RPM의 고정된 연사력과 M416과 유사한 성능을 가지며, 재장전이 다소 느리지만 SCAR-L과 M416의 장점을 조합한 것으로 평가되고 있다. 총기 패치를 통해 장전 시간이 상향되면서 높은 DPS와 준수한 반동 패턴으로 더욱 높은 평가를 받고 있다.',
        'name': 'G36C',
        'image': 'asset/img/g36c.png',
        'ammunition': '5.56mm',
        'ammunition_image': 'asset/img/5탄.png',
        'magazine': '30',
        'shotmode': '단발/연사',
        'damage': '41',
        'muzzleVelocity': '870m/s',
        'stoppingPower': '-',
        'ttk': '0.428s',
        'dps': '478.4',
        'reloadTime': '3.4s',
        'spawnArea': '비켄디, 카라킨, 헤이븐, 데스턴',
        'attachments': [
          'asset/img/레드도트.png',
          'asset/img/홀로그램.png',
          'asset/img/2배율.png',
          'asset/img/3배율.png',
          'asset/img/4배율.png',
          'asset/img/6배율.png',
          'asset/img/캔티드.png',
          'asset/img/열화상4배율.png',
          'asset/img/ar소음기.png',
          'asset/img/ar소염기.png',
          'asset/img/ar보정기.png',
          'asset/img/ar퀴드로우.png',
          'asset/img/ar대탄.png',
          'asset/img/ar대퀵.png',
          'asset/img/앵글.png',
          'asset/img/수직.png',
          'asset/img/하프.png',
          'asset/img/라이트.png',
          'asset/img/엄지.png',
          'asset/img/레이저사이트.png',
        ],
        'attachments_name': [
          '레드 도트 사이트',
          '홀로그램 조준기',
          '2배율 스코프',
          '3배율 스코프',
          '4배율 스코프',
          '6배율 스코프',
          '캔티드 사이트',
          '4배율 열화상 스코프',
          '소음기(AR,DMR,S12K)',
          '소염기(AR,DMR,S12K)',
          '보정기(AR,DMR,S12K)',
          '퀵드로우 탄창(AR,DMR,S12K)',
          '대용량 탄창(AR,DMR,S12K)',
          '대용량 퀵드로우 탄창(AR,DMR,S12K)',
          '앵글 손잡이',
          '수직 손잡이',
          '하프 그립',
          '라이트 그립',
          '엄지 그립',
          '레이저 사이트'
        ],
      },
      {
        'type': 'ar',
        'description': 'Norinco QBZ-95는 5.56mm 탄약을 사용하는 중국 제 돌격소총으로, SCAR-L을 대체하는 총으로 등장하며 높은 드랍율과 상대적으로 높은 탄속을 가지고 있다. 성능은 M416과 SCAR-L의 중간 정도로 평가되며 초반에 무기 부족 시 유용하며 후반까지 사용 가능하나 대미지와 장전 속도의 단점을 유의해야 한다.',
        'name': 'QBZ95',
        'image': 'asset/img/qbz95.png',
        'ammunition': '5.56mm',
        'ammunition_image': 'asset/img/5탄.png',
        'magazine': '30',
        'shotmode': '단발/연사',
        'damage': '42',
        'muzzleVelocity': '930m/s',
        'stoppingPower': '9000',
        'ttk': '0.462s',
        'dps': '455',
        'reloadTime': '3.3s',
        'spawnArea': '사녹, 론도, 태이고',
        'attachments': [
          'asset/img/레드도트.png',
          'asset/img/홀로그램.png',
          'asset/img/2배율.png',
          'asset/img/3배율.png',
          'asset/img/4배율.png',
          'asset/img/6배율.png',
          'asset/img/캔티드.png',
          'asset/img/열화상4배율.png',
          'asset/img/ar소음기.png',
          'asset/img/ar소염기.png',
          'asset/img/ar보정기.png',
          'asset/img/ar퀴드로우.png',
          'asset/img/ar대탄.png',
          'asset/img/ar대퀵.png',
          'asset/img/앵글.png',
          'asset/img/수직.png',
          'asset/img/하프.png',
          'asset/img/라이트.png',
          'asset/img/엄지.png',
          'asset/img/레이저사이트.png',
        ],
        'attachments_name': [
          '레드 도트 사이트',
          '홀로그램 조준기',
          '2배율 스코프',
          '3배율 스코프',
          '4배율 스코프',
          '6배율 스코프',
          '캔티드 사이트',
          '4배율 열화상 스코프',
          '소음기(AR,DMR,S12K)',
          '소염기(AR,DMR,S12K)',
          '보정기(AR,DMR,S12K)',
          '퀵드로우 탄창(AR,DMR,S12K)',
          '대용량 탄창(AR,DMR,S12K)',
          '대용량 퀵드로우 탄창(AR,DMR,S12K)',
          '앵글 손잡이',
          '수직 손잡이',
          '하프 그립',
          '라이트 그립',
          '엄지 그립',
          '레이저 사이트'
        ],
      },
      {
        'type': 'ar',
        'description': '한국산 K2 소총은 배틀그라운드의 한국산 최초 AR로, 파츠 부착이 제한되지만 기본 성능이 준수하며 드랍률이 높아 초반에 유용하다. M416과 비교되며 대미지와 반동이 유사하지만 파츠 부착이 불가능하며 후반에는 경쟁력이 떨어진다. 발사음이 낮고 드랍률이 높아 쉽게 입수할 수 있으며, 초보자에게 적합한 총기로 평가된다.',
        'name': 'K2',
        'image': 'asset/img/k2.png',
        'ammunition': '5.56mm',
        'ammunition_image': 'asset/img/5탄.png',
        'magazine': '30',
        'shotmode': '단발/연사/점사',
        'damage': '41',
        'muzzleVelocity': '880m/s',
        'stoppingPower': '6000',
        'ttk': '0.428s',
        'dps': '478.4',
        'reloadTime': '3.2s',
        'spawnArea': '태이고',
        'attachments': [
          'asset/img/레드도트.png',
          'asset/img/홀로그램.png',
          'asset/img/2배율.png',
          'asset/img/3배율.png',
          'asset/img/4배율.png',
          'asset/img/6배율.png',
          'asset/img/캔티드.png',
          'asset/img/열화상4배율.png',
          'asset/img/ar소음기.png',
          'asset/img/ar소염기.png',
          'asset/img/ar보정기.png',
          'asset/img/ar퀴드로우.png',
          'asset/img/ar대탄.png',
          'asset/img/ar대퀵.png',
        ],
        'attachments_name': [
          '레드 도트 사이트',
          '홀로그램 조준기',
          '2배율 스코프',
          '3배율 스코프',
          '4배율 스코프',
          '6배율 스코프',
          '캔티드 사이트',
          '4배율 열화상 스코프',
          '소음기(AR,DMR,S12K)',
          '소염기(AR,DMR,S12K)',
          '보정기(AR,DMR,S12K)',
          '퀵드로우 탄창(AR,DMR,S12K)',
          '대용량 탄창(AR,DMR,S12K)',
          '대용량 퀵드로우 탄창(AR,DMR,S12K)',
        ],
      },
      {
        'name': 'AUG A3',
        'description': '슈타이어 AUG A3은 필드드랍으로 변경되면서 M416과 M16A4의 중간 연사력을 가지게 되었으며, 5탄 AR 중에서는 빠른 연사속도와 탄속을 가지고 있다. 그러나 소음이 적고 높은 화력을 지녔지만 장전 속도가 느리고 수평 반동이 있는 등 단점도 존재한다. 그럼에도 불구하고 적극적으로 활용할 경우 근중장거리에서 유용하게 사용할 수 있다.',
        'image': 'asset/img/aug_a3.png',
        'ammunition': '5.56mm',
        'ammunition_image': 'asset/img/5탄.png',
        'magazine': '30',
        'shotmode': '단발/연사',
        'damage': '41',
        'muzzleVelocity': '890m/s',
        'stoppingPower': '9000',
        'ttk': '0.425s',
        'dps': '492',
        'reloadTime': '3.6666s',
        'spawnArea': '모든맵',
        'attachments': [
          'asset/img/레드도트.png',
          'asset/img/홀로그램.png',
          'asset/img/2배율.png',
          'asset/img/3배율.png',
          'asset/img/4배율.png',
          'asset/img/6배율.png',
          'asset/img/캔티드.png',
          'asset/img/열화상4배율.png',
          'asset/img/ar소음기.png',
          'asset/img/ar소염기.png',
          'asset/img/ar보정기.png',
          'asset/img/ar퀴드로우.png',
          'asset/img/ar대탄.png',
          'asset/img/ar대퀵.png',
          'asset/img/앵글.png',
          'asset/img/수직.png',
          'asset/img/하프.png',
          'asset/img/라이트.png',
          'asset/img/엄지.png',
          'asset/img/레이저사이트.png',
        ],
        'attachments_name': [
          '레드 도트 사이트',
          '홀로그램 조준기',
          '2배율 스코프',
          '3배율 스코프',
          '4배율 스코프',
          '6배율 스코프',
          '캔티드 사이트',
          '4배율 열화상 스코프',
          '소음기(AR,DMR,S12K)',
          '소염기(AR,DMR,S12K)',
          '보정기(AR,DMR,S12K)',
          '퀵드로우 탄창(AR,DMR,S12K)',
          '대용량 탄창(AR,DMR,S12K)',
          '대용량 퀵드로우 탄창(AR,DMR,S12K)',
          '앵글 손잡이',
          '수직 손잡이',
          '하프 그립',
          '라이트 그립',
          '엄지 그립',
          '레이저 사이트'
        ],
      },
      {
        'type': 'ar',
        'description': 'FAMAS는 높은 연사력과 빠른 RPM로 뛰어난 초당 피해량을 제공하며, 매우 빠른 발사 속도를 통해 화력을 발휘한다. 하지만 대용량 탄창을 착용할 수 없으며, 조준기 디자인의 가시성 문제와 근거리 편중된 사용성으로 인해 전투에서는 제약을 받을 수 있다. 또한 범용성이 낮아 다양한 상황에서 활용이 제한된다.',
        'name': 'FAMAS',
        'image': 'asset/img/famas_g2.png',
        'ammunition': '5.56mm',
        'ammunition_image': 'asset/img/5탄.png',
        'magazine': '30',
        'shotmode': '단발/연사/점사',
        'damage': '39',
        'muzzleVelocity': '925m/s',
        'stoppingPower': '-',
        'ttk': '0.333s',
        'dps': '585',
        'reloadTime': '3.6s',
        'spawnArea': '보급 무기',
        'attachments': [
          'asset/img/레드도트.png',
          'asset/img/홀로그램.png',
          'asset/img/2배율.png',
          'asset/img/3배율.png',
          'asset/img/4배율.png',
          'asset/img/6배율.png',
          'asset/img/캔티드.png',
          'asset/img/열화상4배율.png',
          'asset/img/ar소음기.png',
          'asset/img/ar소염기.png',
          'asset/img/ar보정기.png',
        ],
        'attachments_name': [
          '레드 도트 사이트',
          '홀로그램 조준기',
          '2배율 스코프',
          '3배율 스코프',
          '4배율 스코프',
          '6배율 스코프',
          '캔티드 사이트',
          '4배율 열화상 스코프',
          '소음기(AR,DMR,S12K)',
          '소염기(AR,DMR,S12K)',
          '보정기(AR,DMR,S12K)',
        ],
      },
      {
        'type': 'ar',
        'description': 'AKM은 높은 단발 피해량과 높은 드랍율을 가지며, 초반 근거리 전투에서 탁월한 성능을 발휘한다. 하지만 느린 연사력과 탄속, 낮은 확장성 등의 단점이 있어 중장거리 전투에서는 제약을 받을 수 있다. 그러나 조준 기능을 잘 활용하면 효과적으로 활용할 수 있으며, 후반에는 보정기를 장착하여 반동을 줄이면 좋은 성능을 발휘한다.',
        'name': 'AKM',
        'image': 'asset/img/akm.png',
        'ammunition': '7.62mm',
        'ammunition_image': 'asset/img/7탄.png',
        'magazine': '30',
        'shotmode': '단발/연사',
        'damage': '47',
        'muzzleVelocity': '715m/s',
        'stoppingPower': '10000',
        'ttk': '0.4s',
        'dps': '470',
        'reloadTime': '3.22s',
        'spawnArea': '모든맵',
        'attachments': [
          'asset/img/레드도트.png',
          'asset/img/홀로그램.png',
          'asset/img/2배율.png',
          'asset/img/3배율.png',
          'asset/img/4배율.png',
          'asset/img/6배율.png',
          'asset/img/8배율.png',
          'asset/img/15배율.png',
          'asset/img/캔티드.png',
          'asset/img/열화상4배율.png',
          'asset/img/ar소음기.png',
          'asset/img/ar소염기.png',
          'asset/img/ar보정기.png',
          'asset/img/ar퀴드로우.png',
          'asset/img/ar대탄.png',
          'asset/img/ar대퀵.png',
        ],
        'attachments_name': [
          '레드 도트 사이트',
          '홀로그램 조준기',
          '2배율 스코프',
          '3배율 스코프',
          '4배율 스코프',
          '6배율 스코프',
          '캔티드 사이트',
          '4배율 열화상 스코프',
          '소음기(AR,DMR,S12K)',
          '소염기(AR,DMR,S12K)',
          '보정기(AR,DMR,S12K)',
          '퀵드로우 탄창(AR,DMR,S12K)',
          '대용량 탄창(AR,DMR,S12K)',
          '대용량 퀵드로우 탄창(AR,DMR,S12K)',
        ],
      },
      {
        'type': 'ar',
        'description': '단발, 3점사, 연사의 세 가지 발사 모드를 지원한다. 화력은 뛰어나지만 심한 반동과 파츠 의존성으로 초보 및 중수 유저들에게는 어려움이 있으며, 근거리 전투에서 우수한 성능을 보이나 중거리에서는 반동 제어가 어려워 차선책으로 선택되기도 한다. 유저들 사이에서 평가가 분분하지만, 프로 수준의 반동 제어 능력이 있다면 근거리에서 뛰어난 성능을 발휘할 수 있다.',
        'name': 'Beryl M762',
        'image': 'asset/img/beryl_m762.png',
        'ammunition': '7.62mm',
        'ammunition_image': 'asset/img/7탄.png',
        'magazine': '30',
        'shotmode': '단발/연사/점사',
        'damage': '44',
        'muzzleVelocity': '749m/s',
        'stoppingPower': '10000',
        'ttk': '0.42s',
        'dps': '513.3',
        'reloadTime': '3.1s',
        'spawnArea': '모든맵',
        'attachments': [
          'asset/img/레드도트.png',
          'asset/img/홀로그램.png',
          'asset/img/2배율.png',
          'asset/img/3배율.png',
          'asset/img/4배율.png',
          'asset/img/6배율.png',
          'asset/img/캔티드.png',
          'asset/img/열화상4배율.png',
          'asset/img/ar소음기.png',
          'asset/img/ar소염기.png',
          'asset/img/ar보정기.png',
          'asset/img/ar퀴드로우.png',
          'asset/img/ar대탄.png',
          'asset/img/ar대퀵.png',
          'asset/img/앵글.png',
          'asset/img/수직.png',
          'asset/img/하프.png',
          'asset/img/라이트.png',
          'asset/img/엄지.png',
          'asset/img/레이저사이트.png',
        ],
        'attachments_name': [
          '레드 도트 사이트',
          '홀로그램 조준기',
          '2배율 스코프',
          '3배율 스코프',
          '4배율 스코프',
          '6배율 스코프',
          '캔티드 사이트',
          '4배율 열화상 스코프',
          '소음기(AR,DMR,S12K)',
          '소염기(AR,DMR,S12K)',
          '보정기(AR,DMR,S12K)',
          '퀵드로우 탄창(AR,DMR,S12K)',
          '대용량 탄창(AR,DMR,S12K)',
          '대용량 퀵드로우 탄창(AR,DMR,S12K)',
          '앵글 손잡이',
          '수직 손잡이',
          '하프 그립',
          '라이트 그립',
          '엄지 그립',
          '레이저 사이트'
        ],
      },
      {
        'type': 'ar',
        'description': 'Mk.47 Mutant은 7.62x39mm M43 탄약을 사용하는 AR-10 기반의 소총으로, 단발 및 2점사를 지원한다. 단발 사격이 강점이며, 중장거리에서 뛰어난 성능을 보입니다. 높은 단발 피해량과 확장 가능한 파츠 슬롯이 장점이나 연사 모드가 없고 적은 장탄수로 인해 어려움이 있다. 점사 및 단발 딜레이는 최근 패치로 개선되었으며, 화력은 AR 중 최강으로 평가된다.  단발 및 2점사에 능숙한 유저에게 유용하나 연사 기능 부재와 장탄수의 한계로 인해 활용에 제약이 있다.',
        'name': 'MK47 Mutant',
        'image': 'asset/img/mk47_mutant.png',
        'ammunition': '7.62mm',
        'ammunition_image': 'asset/img/7탄.png',
        'magazine': '20',
        'shotmode': '단발/2점사',
        'damage': '49',
        'muzzleVelocity': '780m/s',
        'stoppingPower': '10000',
        'ttk': '0.3',
        'dps': '653.3',
        'reloadTime': '3.35s',
        'spawnArea': '모든맵',
        'attachments': [
          'asset/img/레드도트.png',
          'asset/img/홀로그램.png',
          'asset/img/2배율.png',
          'asset/img/3배율.png',
          'asset/img/4배율.png',
          'asset/img/6배율.png',
          'asset/img/8배율.png',
          'asset/img/15배율.png',
          'asset/img/캔티드.png',
          'asset/img/열화상4배율.png',
          'asset/img/ar소음기.png',
          'asset/img/ar소염기.png',
          'asset/img/ar보정기.png',
          'asset/img/ar퀴드로우.png',
          'asset/img/ar대탄.png',
          'asset/img/ar대퀵.png',
          'asset/img/개머리판.png',
          'asset/img/중량개머리판.png',
          'asset/img/앵글.png',
          'asset/img/수직.png',
          'asset/img/하프.png',
          'asset/img/라이트.png',
          'asset/img/엄지.png',
          'asset/img/레이저사이트.png',
        ],
        'attachments_name': [
          '레드 도트 사이트',
          '홀로그램 조준기',
          '2배율 스코프',
          '3배율 스코프',
          '4배율 스코프',
          '6배율 스코프',
          '8배율 스코프',
          '15배율 스코프',
          '캔티드 사이트',
          '4배율 열화상 스코프',
          '소음기(AR,DMR,S12K)',
          '소염기(AR,DMR,S12K)',
          '보정기(AR,DMR,S12K)',
          '퀵드로우 탄창(AR,DMR,S12K)',
          '대용량 탄창(AR,DMR,S12K)',
          '대용량 퀵드로우 탄창(AR,DMR,S12K)',
          '전술 개머리판',
          '중량형 개머리판(SMG,AR,M249)',
          '앵글 손잡이',
          '수직 손잡이',
          '하프 그립',
          '라이트 그립',
          '엄지 그립',
          '레이저 사이트'
        ],
      },
      {
        'type': 'ar',
        'description': '그로자는 러시아의 OTs-14-1A-01을 기반으로 한 불펍 카빈으로, 7.62mm 탄약과 높은 연사력으로 강력한 근거리 화력을 자랑한다. 반동이 있으나 장전속도가 빠르고, 범용성이 좋으며 적은 파츠 요구량을 가지고 있다. 그러나 탄속이 느리고 탄약 관리가 어려워 중장거리전에서는 적절한 사용이 필요하다.',
        'name': '그로자',
        'image': 'asset/img/groza.png',
        'ammunition': '7.62mm',
        'ammunition_image': 'asset/img/7탄.png',
        'magazine': '30',
        'shotmode': '단발/연사',
        'damage': '47',
        'muzzleVelocity': '715m/s',
        'stoppingPower': '10000',
        'ttk': '0.32s',
        'dps': '587.5',
        'reloadTime': '3s',
        'spawnArea': '보급 무기',
        'attachments': [
          'asset/img/레드도트.png',
          'asset/img/홀로그램.png',
          'asset/img/2배율.png',
          'asset/img/3배율.png',
          'asset/img/4배율.png',
          'asset/img/6배율.png',
          'asset/img/캔티드.png',
          'asset/img/열화상4배율.png',
          'asset/img/ar소음기.png',
          'asset/img/ar퀴드로우.png',
          'asset/img/ar대탄.png',
          'asset/img/ar대퀵.png',
        ],
        'attachments_name': [
          '레드 도트 사이트',
          '홀로그램 조준기',
          '2배율 스코프',
          '3배율 스코프',
          '4배율 스코프',
          '6배율 스코프',
          '캔티드 사이트',
          '4배율 열화상 스코프',
          '소음기(AR,DMR,S12K)',
          '퀵드로우 탄창(AR,DMR,S12K)',
          '대용량 탄창(AR,DMR,S12K)',
          '대용량 퀵드로우 탄창(AR,DMR,S12K)',
        ],
      },
      {
        'type': 'ar',
        'description': 'ACE32는 7.62mm 탄환을 사용하는 새로운 AR 총기로, 안정적인 반동과 확장 가능한 부착물로 인해 다양한 상황에 유용하다. 그러나 비교적 느린 탄속과 낮은 TTK로 인해 근거리에서는 베릴에 밀리는 경우가 있으며, 올라운더로서의 역할에서 애매한 점이 있다. 부착물에 대한 의존도도 있어 적절한 조작이 필요하다. 그러나 프로들과 스트리머들의 사용 및 추천으로 인해 근중거리 연사에 유리한 선택지로 각광받고 있다.',
        'name': 'ACE32',
        'image': 'asset/img/ace32.png',
        'ammunition': '7.62mm',
        'ammunition_image': 'asset/img/7탄.png',
        'magazine': '30',
        'shotmode': '단발/연사',
        'damage': '43',
        'muzzleVelocity': '720m/s',
        'stoppingPower': '-',
        'ttk': '0.44s',
        'dps': '487.3',
        'reloadTime': '3s',
        'spawnArea': '모든맵',
        'attachments': [
          'asset/img/레드도트.png',
          'asset/img/홀로그램.png',
          'asset/img/2배율.png',
          'asset/img/3배율.png',
          'asset/img/4배율.png',
          'asset/img/6배율.png',
          'asset/img/캔티드.png',
          'asset/img/열화상4배율.png',
          'asset/img/ar소음기.png',
          'asset/img/ar소염기.png',
          'asset/img/ar보정기.png',
          'asset/img/ar퀴드로우.png',
          'asset/img/ar대탄.png',
          'asset/img/ar대퀵.png',
          'asset/img/개머리판.png',
          'asset/img/중량개머리판.png',
          'asset/img/앵글.png',
          'asset/img/수직.png',
          'asset/img/하프.png',
          'asset/img/라이트.png',
          'asset/img/엄지.png',
          'asset/img/레이저사이트.png',
        ],
        'attachments_name': [
          '레드 도트 사이트',
          '홀로그램 조준기',
          '2배율 스코프',
          '3배율 스코프',
          '4배율 스코프',
          '6배율 스코프',
          '캔티드 사이트',
          '4배율 열화상 스코프',
          '소음기(AR,DMR,S12K)',
          '소염기(AR,DMR,S12K)',
          '보정기(AR,DMR,S12K)',
          '퀵드로우 탄창(AR,DMR,S12K)',
          '대용량 탄창(AR,DMR,S12K)',
          '대용량 퀵드로우 탄창(AR,DMR,S12K)',
          '전술 개머리판',
          '중량형 개머리판(SMG,AR,M249)',
          '앵글 손잡이',
          '수직 손잡이',
          '하프 그립',
          '라이트 그립',
          '엄지 그립',
          '레이저 사이트'
        ],
      },
    ];

    return SafeArea(
      child: Scaffold(
        backgroundColor: Color(0xFFF2AA00), // 배경색을 검정색으로 설정합니다.
        appBar: AppBar(
          backgroundColor: Colors.black,
          title: Text(
            'AR - 돌격 소총',
            style: textStyle,
          ),
        ),
        body: Padding(
          padding: const EdgeInsets.all(8.0), // 그리드에 패딩을 추가합니다.
          child: GridView.builder(
            gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
              crossAxisCount: 3, // 3개의 열을 가진 그리드 뷰를 생성합니다.
              childAspectRatio: 0.75, // 셀의 가로 세로 비율을 조정합니다.
            ),
            itemCount: gunList.length, // 총기의 갯수만큼 아이템을 생성합니다.
            itemBuilder: (context, index) {
              return Card(
                // 카드 위젯을 사용하여 각 항목을 감쌉니다.
                color: Colors.grey[900], // 카드 배경색을 설정합니다.
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center, // 센터 정렬을 적용합니다.
                  children: [
                    Expanded(
                      child: IconButton(
                        icon: Image.asset(
                          gunList[index]['image']!, // 이미지 경로를 사용합니다.
                          fit: BoxFit.contain, // 이미지를 비율에 맞게 조정합니다.
                        ),
                        iconSize: 200, // 아이콘의 크기를 지정합니다.
                        onPressed: () {
                          Navigator.of(context).push(
                            MaterialPageRoute(
                                builder: (_) =>
                                    GunInfoScreen(gunData: gunList[index])),
                          );
                        },
                      ),
                    ),
                    Text(
                      gunList[index]['name']!, // 총기의 이름을 표시합니다.
                      style: textStyle,
                    ),
                  ],
                ),
              );
            },
          ),
        ),
      ),
    );
  }
}
