import 'package:flutter/material.dart';
import 'gun_info.dart';

class DmrScreen extends StatelessWidget {
  const DmrScreen({super.key});

  @override
  Widget build(BuildContext context) {
    TextStyle textStyle = TextStyle(
      color: Colors.white,
      fontSize: 15.0,
      fontWeight: FontWeight.w700,
    );

    // 총기 리스트를 정의합니다.
    final List<Map<String, dynamic>> gunList = [
      {
        'type': 'dmr',
        'description': '2017년 9월 14일 업데이트로 추가된 DMR으로, 5.56mm 탄약을 사용하여 탄속이 빠르고 반동이 낮으며, 장탄수도 20발로 많아 AR처럼 사격이 가능하다. 피해량은 7.62mm 탄약을 쓰는 DMR에 비해 낮지만, 빠른 탄속과 높은 장탄수로 인해 중장거리에서 효과적이다. 또한 탄속이 게임 내 2위로 매우 빠르고, 장탄수도 DMR 중 최고로 높아 원거리 교전에 적합하며, 반동도 낮아 조정이 쉽다. 그러나 대미지는 낮고 장전시간이 길어 피해량 타이도 작아지고 장전 중에 적을 놓칠 수 있다.',
        'name': 'Mini14',
        'ammunition': '5.56mm',
        'ammunition_image': 'asset/img/5탄.png',
        'image': 'asset/img/미니.png',
        'magazine': '20',
        'shotmode': '단발',
        'damage': '48',
        'muzzleVelocity': '990m/s',
        'stoppingPower': '10000',
        'ttk': '0.4',
        'dps': '504',
        'reloadTime': '3.6s',
        'spawnArea': '모든맵(사녹 제외)',
        'attachments': [
          'asset/img/레드도트.png',
          'asset/img/홀로그램.png',
          'asset/img/2배율.png',
          'asset/img/3배율.png',
          'asset/img/4배율.png',
          'asset/img/6배율.png',
          'asset/img/8배율.png',
          'asset/img/15배율.png',
          'asset/img/캔티드.png',
          'asset/img/열화상4배율.png',
          'asset/img/ar소음기.png',
          'asset/img/ar소염기.png',
          'asset/img/ar보정기.png',
          'asset/img/sr소음기.png',
          'asset/img/sr소염기.png',
          'asset/img/sr보정기.png',
          'asset/img/ar퀴드로우.png',
          'asset/img/ar대탄.png',
          'asset/img/ar대퀵.png',
          'asset/img/sr대탄.png',
          'asset/img/sr대퀵.png',
        ],
        'attachments_name': [
          '레드 도트 사이트',
          '홀로그램 조준기',
          '2배율 스코프',
          '3배율 스코프',
          '4배율 스코프',
          '6배율 스코프',
          '8배율 스코프',
          '15배율 스코프',
          '캔티드 사이트',
          '4배율 열화상 스코프',
          '소음기(AR,DMR,S12K)',
          '소염기(AR,DMR,S12K)',
          '보정기(AR,DMR,S12K)',
          '소음기(SR,DMR)',
          '소염기(SR,DMR)',
          '보정기(SR,DMR)',
          '퀵드로우 탄창(AR,DMR,S12K)',
          '대용량 탄창(AR,DMR,S12K)',
          '대용량 퀵드로우 탄창(AR,DMR,S12K)',
          '대용량 탄창(SR,DMR)',
          '대용량 퀵드로우 탄창(SR,DMR)',
        ],
      },
      {
        'type': 'DMR',
        'description': '18차 패치노트에서 추가된 DMR인 QBU는 Mini-14 대신 등장하며, 5.56mm 탄을 사용한다. 사녹에서만 사용 가능하며, Mini-14와 대체적으로 유사한 성능을 보이지만 장탄수가 적고 반동이 크다. 특이하게도 양각대를 부착하여 엎드려서 사격하면 반동이 크게 줄어든다. 소음효과가 뛰어나지만 실제로는 그렇게 뚜렷하지 않으며, 사녹의 조건에서만 적합하다.',
        'name': 'QBU88',
        'ammunition': '5.56mm',
        'ammunition_image': 'asset/img/5탄.png',
        'image': 'asset/img/qbu.png',
        'magazine': '10',
        'shotmode': '단발',
        'damage': 48,
        'muzzleVelocity': '990m/s',
        'stoppingPower': '10000',
        'ttk': '0.4',
        'dps': '504',
        'reloadTime': '3s',
        'spawnArea': '사녹, 론도',
        'attachments': [
          'asset/img/레드도트.png',
          'asset/img/홀로그램.png',
          'asset/img/2배율.png',
          'asset/img/3배율.png',
          'asset/img/4배율.png',
          'asset/img/6배율.png',
          'asset/img/8배율.png',
          'asset/img/15배율.png',
          'asset/img/캔티드.png',
          'asset/img/열화상4배율.png',
          'asset/img/ar소음기.png',
          'asset/img/ar소염기.png',
          'asset/img/ar보정기.png',
          'asset/img/sr소음기.png',
          'asset/img/sr소염기.png',
          'asset/img/sr보정기.png',
          'asset/img/ar퀴드로우.png',
          'asset/img/ar대탄.png',
          'asset/img/ar대퀵.png',
          'asset/img/sr대탄.png',
          'asset/img/sr대퀵.png',
        ],
        'attachments_name': [
          '레드 도트 사이트',
          '홀로그램 조준기',
          '2배율 스코프',
          '3배율 스코프',
          '4배율 스코프',
          '6배율 스코프',
          '8배율 스코프',
          '15배율 스코프',
          '캔티드 사이트',
          '4배율 열화상 스코프',
          '소음기(AR,DMR,S12K)',
          '소염기(AR,DMR,S12K)',
          '보정기(AR,DMR,S12K)',
          '소음기(SR,DMR)',
          '소염기(SR,DMR)',
          '보정기(SR,DMR)',
          '퀵드로우 탄창(AR,DMR,S12K)',
          '대용량 탄창(AR,DMR,S12K)',
          '대용량 퀵드로우 탄창(AR,DMR,S12K)',
          '대용량 탄창(SR,DMR)',
          '대용량 퀵드로우 탄창(SR,DMR)',
        ],
      },
      {
        'type': 'dmr',
        'description': 'Mk12은 5.56mm 탄을 사용하는 DMR 중 최초로 양각대와 손잡이를 지원하며, 탄속은 미니14보다 낮지만 피해량은 미니14와 QBU의 중간인 51을 가지고 있다. 손잡이를 장착하면 반동이 감소하며, 소음기를 장착하면 소음 효과가 뛰어나다. PC와 콘솔판에서는 16.1 패치로 성능이 향상되어 이용률이 증가하고, 20.1 패치로 라이트 그립이 단발 사격에 더욱 특화되었다. 그러나 탄속은 미니14와 QBU보다 느리고, 반동이 다소 심하다.',
        'name': 'MK12',
        'ammunition': '5.56mm',
        'ammunition_image': 'asset/img/5탄.png',
        'image': 'asset/img/mk12.png',
        'magazine': '20',
        'shotmode': '단발',
        'damage': '50',
        'muzzleVelocity': '900m/s',
        'stoppingPower': '10000',
        'ttk': '0.5',
        'dps': '535.5',
        'reloadTime': '2.6s',
        'spawnArea': '모든맵',
        'attachments': [
          'asset/img/레드도트.png',
          'asset/img/홀로그램.png',
          'asset/img/2배율.png',
          'asset/img/3배율.png',
          'asset/img/4배율.png',
          'asset/img/6배율.png',
          'asset/img/8배율.png',
          'asset/img/15배율.png',
          'asset/img/캔티드.png',
          'asset/img/열화상4배율.png',
          'asset/img/ar소음기.png',
          'asset/img/ar소염기.png',
          'asset/img/ar보정기.png',
          'asset/img/sr소음기.png',
          'asset/img/sr소염기.png',
          'asset/img/sr보정기.png',
          'asset/img/ar퀴드로우.png',
          'asset/img/ar대탄.png',
          'asset/img/ar대퀵.png',
          'asset/img/sr대탄.png',
          'asset/img/sr대퀵.png',
          'asset/img/앵글.png',
          'asset/img/수직.png',
          'asset/img/하프.png',
          'asset/img/라이트.png',
          'asset/img/엄지.png',
          'asset/img/레이저사이트.png',
        ],
        'attachments_name': [
          '레드 도트 사이트',
          '홀로그램 조준기',
          '2배율 스코프',
          '3배율 스코프',
          '4배율 스코프',
          '6배율 스코프',
          '8배율 스코프',
          '15배율 스코프',
          '캔티드 사이트',
          '4배율 열화상 스코프',
          '소음기(AR,DMR,S12K)',
          '소염기(AR,DMR,S12K)',
          '보정기(AR,DMR,S12K)',
          '소음기(SR,DMR)',
          '소염기(SR,DMR)',
          '보정기(SR,DMR)',
          '퀵드로우 탄창(AR,DMR,S12K)',
          '대용량 탄창(AR,DMR,S12K)',
          '대용량 퀵드로우 탄창(AR,DMR,S12K)',
          '대용량 탄창(SR,DMR)',
          '대용량 퀵드로우 탄창(SR,DMR)',
          '앵글 손잡이',
          '수직 손잡이',
          '하프 그립',
          '라이트 그립',
          '엄지 그립',
          '레이저 사이트'
        ],
      },
      {
        'type': 'dmr',
        'description': 'SKS는 얼리 엑세스 당시에 추가된 반자동 DMR 중 최초로 필드 드롭으로 얻을 수 있는 총기이다. 기본 장탄수는 10발이지만 대용량 탄창을 장착하여 20발까지 증가할 수 있어 지속 화력이 우수하다. 손잡이로는 수직 손잡이와 라이트 그립이 가장 어울리며, 상대적으로 높은 DPS와 빠른 광클로 중거리 전투에서 강력한 올라운더 무기로서 활용된다. 그러나 다른 DMR에 비해 탄속이 낮고 낙차가 있어 중장거리 전투에서는 약간의 불리함을 겪을 수 있다.',
        'name': 'SKS',
        'ammunition': '7.62mm',
        'ammunition_image': 'asset/img/7탄.png',
        'image': 'asset/img/sks.png',
        'magazine': '10',
        'shotmode': '단발',
        'damage': '53',
        'muzzleVelocity': '800m/s',
        'stoppingPower': '20000',
        'ttk': '0.27',
        'dps': '588.9',
        'reloadTime': '2.9s',
        'spawnArea': '모든맵',
        'attachments': [
          'asset/img/레드도트.png',
          'asset/img/홀로그램.png',
          'asset/img/2배율.png',
          'asset/img/3배율.png',
          'asset/img/4배율.png',
          'asset/img/6배율.png',
          'asset/img/8배율.png',
          'asset/img/15배율.png',
          'asset/img/캔티드.png',
          'asset/img/열화상4배율.png',
          'asset/img/ar소음기.png',
          'asset/img/ar소염기.png',
          'asset/img/ar보정기.png',
          'asset/img/sr소음기.png',
          'asset/img/sr소염기.png',
          'asset/img/sr보정기.png',
          'asset/img/ar퀴드로우.png',
          'asset/img/ar대탄.png',
          'asset/img/ar대퀵.png',
          'asset/img/sr대탄.png',
          'asset/img/sr대퀵.png',
          'asset/img/칙패드.png',
          'asset/img/앵글.png',
          'asset/img/수직.png',
          'asset/img/하프.png',
          'asset/img/라이트.png',
          'asset/img/엄지.png',
          'asset/img/레이저사이트.png',
        ],
        'attachments_name': [
          '레드 도트 사이트',
          '홀로그램 조준기',
          '2배율 스코프',
          '3배율 스코프',
          '4배율 스코프',
          '6배율 스코프',
          '8배율 스코프',
          '15배율 스코프',
          '캔티드 사이트',
          '4배율 열화상 스코프',
          '소음기(AR,DMR,S12K)',
          '소염기(AR,DMR,S12K)',
          '보정기(AR,DMR,S12K)',
          '소음기(SR,DMR)',
          '소염기(SR,DMR)',
          '보정기(SR,DMR)',
          '퀵드로우 탄창(AR,DMR,S12K)',
          '대용량 탄창(AR,DMR,S12K)',
          '대용량 퀵드로우 탄창(AR,DMR,S12K)',
          '대용량 탄창(SR,DMR)',
          '대용량 퀵드로우 탄창(SR,DMR)',
          '칙패드',
          '앵글 손잡이',
          '수직 손잡이',
          '하프 그립',
          '라이트 그립',
          '엄지 그립',
          '레이저 사이트'
        ],
      },
      {
        'type': 'dmr',
        'description': 'Mk14는 보급상자에서만 얻을 수 있는 DMR로, 높은 피해량과 빠른 탄속을 가졌으며 8배율 연사가 가능하다. 그러나 심한 반동과 부족한 장탄수가 단점으로 작용하며, 연사 시 재장전이 빈번하게 필요하다. 높은 피해량과 초당 피해량으로 중장거리 전투에서 우수한 성능을 보이지만, 반동이 강력하여 연사를 사용할 경우에는 근접 전투에 적합하지 않다. 전반적으로 근, 중, 원거리에서 모두 활용 가능한 만능적인 총기이지만, 연사로 사용 시 재장전이나 반동 관리에 주의해야 한다.',
        'name': 'MK14',
        'ammunition': '7.62mm',
        'ammunition_image': 'asset/img/7탄.png',
        'image': 'asset/img/mk14.png',
        'magazine': '10',
        'shotmode': '단발/연사',
        'damage': '61',
        'muzzleVelocity': '853m/s',
        'stoppingPower': '20000',
        'ttk': '0.27',
        'dps': '712',
        'reloadTime': '3.683s',
        'spawnArea': '보급 무기',
        'attachments': [
          'asset/img/레드도트.png',
          'asset/img/홀로그램.png',
          'asset/img/2배율.png',
          'asset/img/3배율.png',
          'asset/img/4배율.png',
          'asset/img/6배율.png',
          'asset/img/8배율.png',
          'asset/img/15배율.png',
          'asset/img/캔티드.png',
          'asset/img/열화상4배율.png',
          'asset/img/ar소음기.png',
          'asset/img/ar소염기.png',
          'asset/img/ar보정기.png',
          'asset/img/sr소음기.png',
          'asset/img/sr소염기.png',
          'asset/img/sr보정기.png',
          'asset/img/ar퀴드로우.png',
          'asset/img/ar대탄.png',
          'asset/img/ar대퀵.png',
          'asset/img/sr대탄.png',
          'asset/img/sr대퀵.png',
          'asset/img/칙패드.png',
        ],
        'attachments_name': [
          '레드 도트 사이트',
          '홀로그램 조준기',
          '2배율 스코프',
          '3배율 스코프',
          '4배율 스코프',
          '6배율 스코프',
          '8배율 스코프',
          '15배율 스코프',
          '캔티드 사이트',
          '4배율 열화상 스코프',
          '소음기(AR,DMR,S12K)',
          '소염기(AR,DMR,S12K)',
          '보정기(AR,DMR,S12K)',
          '소음기(SR,DMR)',
          '소염기(SR,DMR)',
          '보정기(SR,DMR)',
          '퀵드로우 탄창(AR,DMR,S12K)',
          '대용량 탄창(AR,DMR,S12K)',
          '대용량 퀵드로우 탄창(AR,DMR,S12K)',
          '대용량 탄창(SR,DMR)',
          '대용량 퀵드로우 탄창(SR,DMR)',
          '칙패드',
        ],
      },
      {
        'type': 'dmr',
        'description': 'SLR은 SKS와 MK14 사이의 DMR으로, 높은 피해량과 빠른 탄속을 가지고 있으며 연발 사격 시에도 효과적이다. 그러나 반동이 강하고 드랍률이 낮아 초보자에게는 적합하지 않으며, 광클로 속사하기 어렵고 연발 간격이 길어 연사로 사용하기에도 어려움을 겪을 수 있다. SKS와 비교했을 때 대미지, 파츠 장착, 탄속 부분들에서 우위룰 가지기 때문에 SLR을 더 많이 사용한다.',
        'name': 'SLR',
        'ammunition': '7.62mm',
        'ammunition_image': 'asset/img/7탄.png',
        'image': 'asset/img/slr.png',
        'magazine': '10',
        'shotmode': '단발',
        'damage': '56',
        'muzzleVelocity': '840m/s',
        'stoppingPower': '20000',
        'ttk': '0.33',
        'dps': '509.1',
        'reloadTime': '3.1s',
        'spawnArea': '모든맵',
        'attachments': [
          'asset/img/레드도트.png',
          'asset/img/홀로그램.png',
          'asset/img/2배율.png',
          'asset/img/3배율.png',
          'asset/img/4배율.png',
          'asset/img/6배율.png',
          'asset/img/8배율.png',
          'asset/img/15배율.png',
          'asset/img/캔티드.png',
          'asset/img/열화상4배율.png',
          'asset/img/ar소음기.png',
          'asset/img/ar소염기.png',
          'asset/img/ar보정기.png',
          'asset/img/sr소음기.png',
          'asset/img/sr소염기.png',
          'asset/img/sr보정기.png',
          'asset/img/ar퀴드로우.png',
          'asset/img/ar대탄.png',
          'asset/img/ar대퀵.png',
          'asset/img/sr대탄.png',
          'asset/img/sr대퀵.png',
          'asset/img/칙패드.png',
        ],
        'attachments_name': [
          '레드 도트 사이트',
          '홀로그램 조준기',
          '2배율 스코프',
          '3배율 스코프',
          '4배율 스코프',
          '6배율 스코프',
          '8배율 스코프',
          '15배율 스코프',
          '캔티드 사이트',
          '4배율 열화상 스코프',
          '소음기(AR,DMR,S12K)',
          '소염기(AR,DMR,S12K)',
          '보정기(AR,DMR,S12K)',
          '소음기(SR,DMR)',
          '소염기(SR,DMR)',
          '보정기(SR,DMR)',
          '퀵드로우 탄창(AR,DMR,S12K)',
          '대용량 탄창(AR,DMR,S12K)',
          '대용량 퀵드로우 탄창(AR,DMR,S12K)',
          '대용량 탄창(SR,DMR)',
          '대용량 퀵드로우 탄창(SR,DMR)',
          '칙패드',
        ],
      },
      {
        'type': 'dmr',
        'description': '드라구노프는 소련 제 지정사수 소총으로 7탄을 사용하는 DMR이다. 높은 몸통 기본 피해량을 가졌지만 반동이 높고 연발 속도가 낮아 광클로 속사가 불가능하며, 헤드샷 명중 시 높은 피해량을 가지고 있다. 근-중거리 교전에서 유용하며,100M안에서  2레벨 헬멧 착용 적을 한 발에 눕힐 수 있다. 하지만 중거리 이상에서는 성능이 제한되며, SR과 DMR 사이의 총기로 특히 근거리에서 활약한다. 후반부 장기장 근거리 교전에서 피킹전에서 2레벨 헬멧 한방이라는 우위를 가질 수 있다.',
        'name': '드라구노프',
        'ammunition': '7.62mm',
        'ammunition_image': 'asset/img/7탄.png',
        'image': 'asset/img/드라구노프.png',
        'magazine': '10',
        'shotmode': '단발',
        'damage': '60',
        'muzzleVelocity': '830m/s',
        'stoppingPower': '-',
        'ttk': '1.2',
        'dps': '157.5',
        'reloadTime': '3.4s',
        'spawnArea': '모든맵',
        'attachments': [
          'asset/img/레드도트.png',
          'asset/img/홀로그램.png',
          'asset/img/2배율.png',
          'asset/img/3배율.png',
          'asset/img/4배율.png',
          'asset/img/6배율.png',
          'asset/img/8배율.png',
          'asset/img/15배율.png',
          'asset/img/캔티드.png',
          'asset/img/열화상4배율.png',
          'asset/img/ar소음기.png',
          'asset/img/ar소염기.png',
          'asset/img/ar보정기.png',
          'asset/img/sr소음기.png',
          'asset/img/sr소염기.png',
          'asset/img/sr보정기.png',
          'asset/img/ar퀴드로우.png',
          'asset/img/ar대탄.png',
          'asset/img/ar대퀵.png',
          'asset/img/sr대탄.png',
          'asset/img/sr대퀵.png',
          'asset/img/칙패드.png',
        ],
        'attachments_name': [
          '레드 도트 사이트',
          '홀로그램 조준기',
          '2배율 스코프',
          '3배율 스코프',
          '4배율 스코프',
          '6배율 스코프',
          '8배율 스코프',
          '15배율 스코프',
          '캔티드 사이트',
          '4배율 열화상 스코프',
          '소음기(AR,DMR,S12K)',
          '소염기(AR,DMR,S12K)',
          '보정기(AR,DMR,S12K)',
          '소음기(SR,DMR)',
          '소염기(SR,DMR)',
          '보정기(SR,DMR)',
          '퀵드로우 탄창(AR,DMR,S12K)',
          '대용량 탄창(AR,DMR,S12K)',
          '대용량 퀵드로우 탄창(AR,DMR,S12K)',
          '대용량 탄창(SR,DMR)',
          '대용량 퀵드로우 탄창(SR,DMR)',
          '칙패드',
        ],
      },
      {
        'type': 'dmr',
        'description': 'VSS는 PSO-1 4배율 조준경과 소음기가 기본 장착된 러시아 제 저격 소총으로, 낮은 확률로 드랍된다. 9mm 탄을 사용하며 소음과 반동이 적지만 피해량은 낮으며, 총기의 독특한 특성으로 인해 전투에서 특별한 운용법이 요구된다. 은밀한 암살과 근거리 전투에서 강점을 보이지만, 대량의 탄창을 갖지 않고 느린 탄속으로 중장거리에서는 적응이 필요하며, 다대다 전에서는 상대적으로 효과가 떨어진다. 요약하면 VSS는 은밀한 플레이와 근거리 전투에서 빛을 발하는 독특한 무기이다.',
        'name': 'VSS',
        'ammunition': '9mm',
        'ammunition_image': 'asset/img/9탄.png',
        'image': 'asset/img/vss.png',
        'magazine': '10',
        'shotmode': '단발/연사',
        'damage': '43',
        'muzzleVelocity': '330m/s',
        'stoppingPower': '20000',
        'ttk': '0.344',
        'dps': '504',
        'reloadTime': '3.5s',
        'spawnArea': '모든맵(카라킨 제외)',
        'attachments': [
          'asset/img/캔티드.png',
          'asset/img/ar퀴드로우.png',
          'asset/img/ar대탄.png',
          'asset/img/ar대퀵.png',
          'asset/img/sr대탄.png',
          'asset/img/sr대퀵.png',
          'asset/img/칙패드.png',
        ],
        'attachments_name': [
          '캔티드 사이트',
          '퀵드로우 탄창(AR,DMR,S12K)',
          '대용량 탄창(AR,DMR,S12K)',
          '대용량 퀵드로우 탄창(AR,DMR,S12K)',
          '대용량 탄창(SR,DMR)',
          '대용량 퀵드로우 탄창(SR,DMR)',
          '칙패드',
        ],
      },
    ];

    return SafeArea(
      child: Scaffold(
        backgroundColor: Color(0xFFF2AA00), // 배경색을 검정색으로 설정합니다.
        appBar: AppBar(
          backgroundColor: Colors.black,
          title: Text(
            'DMR - 저격 소총',
            style: textStyle,
          ),
        ),
        body: Padding(
          padding: const EdgeInsets.all(8.0), // 그리드에 패딩을 추가합니다.
          child: GridView.builder(
            gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
              crossAxisCount: 3, // 3개의 열을 가진 그리드 뷰를 생성합니다.
              childAspectRatio: 0.75, // 셀의 가로 세로 비율을 조정합니다.
            ),
            itemCount: gunList.length, // 총기의 갯수만큼 아이템을 생성합니다.
            itemBuilder: (context, index) {
              return Card(
                // 카드 위젯을 사용하여 각 항목을 감쌉니다.
                color: Colors.grey[900], // 카드 배경색을 설정합니다.
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center, // 센터 정렬을 적용합니다.
                  children: [
                    Expanded(
                      child: IconButton(
                        icon: Image.asset(
                          gunList[index]['image']!, // 이미지 경로를 사용합니다.
                          fit: BoxFit.contain, // 이미지를 비율에 맞게 조정합니다.
                        ),
                        iconSize: 200, // 아이콘의 크기를 지정합니다.
                        onPressed: () {
                          Navigator.of(context).push(
                            MaterialPageRoute(
                                builder: (_) =>
                                    GunInfoScreen(gunData: gunList[index])),
                          );
                        },
                      ),
                    ),
                    Text(
                      gunList[index]['name']!, // 총기의 이름을 표시합니다.
                      style: textStyle,
                    ),
                  ],
                ),
              );
            },
          ),
        ),
      ),
    );
  }
}
