import 'package:flutter/material.dart';
import 'gun_info.dart';

class DmrScreen extends StatelessWidget {
  const DmrScreen({super.key});

  @override
  Widget build(BuildContext context) {
    TextStyle textStyle = TextStyle(
      color: Colors.white,
      fontSize: 15.0,
      fontWeight: FontWeight.w700,
    );

    // 총기 리스트를 정의합니다.
    final List<Map<String, dynamic>> gunList = [
      {
        'type': 'dmr',
        'name': 'Mini14',
        'ammunition': '5.56mm',
        'ammunition_image': 'asset/img/5탄.png',
        'image': 'asset/img/미니.png',
        'magazine': '20',
        'shotmode': '단발',
        'damage': '48',
        'muzzleVelocity': '990m/s',
        'stoppingPower': '10000',
        'ttk': '0.4',
        'dps': '504',
        'reloadTime': '3.6s',
        'spawnArea': '모든맵(사녹 제외)',
        'attachments': [
          'asset/img/레드도트.png',
          'asset/img/홀로그램.png',
          'asset/img/2배율.png',
          'asset/img/3배율.png',
          'asset/img/4배율.png',
          'asset/img/6배율.png',
          'asset/img/8배율.png',
          'asset/img/15배율.png',
          'asset/img/캔티드.png',
          'asset/img/열화상4배율.png',
          'asset/img/ar소음기.png',
          'asset/img/ar소염기.png',
          'asset/img/ar보정기.png',
          'asset/img/sr소음기.png',
          'asset/img/sr소염기.png',
          'asset/img/sr보정기.png',
          'asset/img/ar퀴드로우.png',
          'asset/img/ar대탄.png',
          'asset/img/ar대퀵.png',
          'asset/img/sr대탄.png',
          'asset/img/sr대퀵.png',
        ],
        'attachments_name': [
          '레드 도트 사이트',
          '홀로그램 조준기',
          '2배율 스코프',
          '3배율 스코프',
          '4배율 스코프',
          '6배율 스코프',
          '8배율 스코프',
          '15배율 스코프',
          '캔티드 사이트',
          '4배율 열화상 스코프',
          '소음기(AR,DMR,S12K)',
          '소염기(AR,DMR,S12K)',
          '보정기(AR,DMR,S12K)',
          '소음기(SR,DMR)',
          '소염기(SR,DMR)',
          '보정기(SR,DMR)',
          '퀵드로우 탄창(AR,DMR,S12K)',
          '대용량 탄창(AR,DMR,S12K)',
          '대용량 퀵드로우 탄창(AR,DMR,S12K)',
          '대용량 탄창(SR,DMR)',
          '대용량 퀵드로우 탄창(SR,DMR)',
        ],
      },
      {
        'type': 'DMR',
        'name': 'QBU88',
        'ammunition': '5.56mm',
        'ammunition_image': 'asset/img/5탄.png',
        'image': 'asset/img/qbu.png',
        'magazine': '10',
        'shotmode': '단발',
        'damage': 48,
        'muzzleVelocity': '990m/s',
        'stoppingPower': '10000',
        'ttk': '0.4',
        'dps': '504',
        'reloadTime': '3s',
        'spawnArea': '사녹, 론도',
        'attachments': [
          'asset/img/레드도트.png',
          'asset/img/홀로그램.png',
          'asset/img/2배율.png',
          'asset/img/3배율.png',
          'asset/img/4배율.png',
          'asset/img/6배율.png',
          'asset/img/8배율.png',
          'asset/img/15배율.png',
          'asset/img/캔티드.png',
          'asset/img/열화상4배율.png',
          'asset/img/ar소음기.png',
          'asset/img/ar소염기.png',
          'asset/img/ar보정기.png',
          'asset/img/sr소음기.png',
          'asset/img/sr소염기.png',
          'asset/img/sr보정기.png',
          'asset/img/ar퀴드로우.png',
          'asset/img/ar대탄.png',
          'asset/img/ar대퀵.png',
          'asset/img/sr대탄.png',
          'asset/img/sr대퀵.png',
        ],
        'attachments_name': [
          '레드 도트 사이트',
          '홀로그램 조준기',
          '2배율 스코프',
          '3배율 스코프',
          '4배율 스코프',
          '6배율 스코프',
          '8배율 스코프',
          '15배율 스코프',
          '캔티드 사이트',
          '4배율 열화상 스코프',
          '소음기(AR,DMR,S12K)',
          '소염기(AR,DMR,S12K)',
          '보정기(AR,DMR,S12K)',
          '소음기(SR,DMR)',
          '소염기(SR,DMR)',
          '보정기(SR,DMR)',
          '퀵드로우 탄창(AR,DMR,S12K)',
          '대용량 탄창(AR,DMR,S12K)',
          '대용량 퀵드로우 탄창(AR,DMR,S12K)',
          '대용량 탄창(SR,DMR)',
          '대용량 퀵드로우 탄창(SR,DMR)',
        ],
      },
      {
        'type': 'dmr',
        'name': 'MK12',
        'ammunition': '5.56mm',
        'ammunition_image': 'asset/img/5탄.png',
        'image': 'asset/img/mk12.png',
        'magazine': '20',
        'shotmode': '단발',
        'damage': '50',
        'muzzleVelocity': '900m/s',
        'stoppingPower': '10000',
        'ttk': '0.5',
        'dps': '535.5',
        'reloadTime': '2.6s',
        'spawnArea': '모든맵',
        'attachments': [
          'asset/img/레드도트.png',
          'asset/img/홀로그램.png',
          'asset/img/2배율.png',
          'asset/img/3배율.png',
          'asset/img/4배율.png',
          'asset/img/6배율.png',
          'asset/img/8배율.png',
          'asset/img/15배율.png',
          'asset/img/캔티드.png',
          'asset/img/열화상4배율.png',
          'asset/img/ar소음기.png',
          'asset/img/ar소염기.png',
          'asset/img/ar보정기.png',
          'asset/img/sr소음기.png',
          'asset/img/sr소염기.png',
          'asset/img/sr보정기.png',
          'asset/img/ar퀴드로우.png',
          'asset/img/ar대탄.png',
          'asset/img/ar대퀵.png',
          'asset/img/sr대탄.png',
          'asset/img/sr대퀵.png',
          'asset/img/앵글.png',
          'asset/img/수직.png',
          'asset/img/하프.png',
          'asset/img/라이트.png',
          'asset/img/엄지.png',
          'asset/img/레이저사이트.png',
        ],
        'attachments_name': [
          '레드 도트 사이트',
          '홀로그램 조준기',
          '2배율 스코프',
          '3배율 스코프',
          '4배율 스코프',
          '6배율 스코프',
          '8배율 스코프',
          '15배율 스코프',
          '캔티드 사이트',
          '4배율 열화상 스코프',
          '소음기(AR,DMR,S12K)',
          '소염기(AR,DMR,S12K)',
          '보정기(AR,DMR,S12K)',
          '소음기(SR,DMR)',
          '소염기(SR,DMR)',
          '보정기(SR,DMR)',
          '퀵드로우 탄창(AR,DMR,S12K)',
          '대용량 탄창(AR,DMR,S12K)',
          '대용량 퀵드로우 탄창(AR,DMR,S12K)',
          '대용량 탄창(SR,DMR)',
          '대용량 퀵드로우 탄창(SR,DMR)',
          '앵글 손잡이',
          '수직 손잡이',
          '하프 그립',
          '라이트 그립',
          '엄지 그립',
          '레이저 사이트'
        ],
      },
      {
        'type': 'dmr',
        'name': 'SKS',
        'ammunition': '7.62mm',
        'ammunition_image': 'asset/img/7탄.png',
        'image': 'asset/img/sks.png',
        'magazine': '10',
        'shotmode': '단발',
        'damage': '53',
        'muzzleVelocity': '800m/s',
        'stoppingPower': '20000',
        'ttk': '0.27',
        'dps': '588.9',
        'reloadTime': '2.9s',
        'spawnArea': '모든맵',
        'attachments': [
          'asset/img/레드도트.png',
          'asset/img/홀로그램.png',
          'asset/img/2배율.png',
          'asset/img/3배율.png',
          'asset/img/4배율.png',
          'asset/img/6배율.png',
          'asset/img/8배율.png',
          'asset/img/15배율.png',
          'asset/img/캔티드.png',
          'asset/img/열화상4배율.png',
          'asset/img/ar소음기.png',
          'asset/img/ar소염기.png',
          'asset/img/ar보정기.png',
          'asset/img/sr소음기.png',
          'asset/img/sr소염기.png',
          'asset/img/sr보정기.png',
          'asset/img/ar퀴드로우.png',
          'asset/img/ar대탄.png',
          'asset/img/ar대퀵.png',
          'asset/img/sr대탄.png',
          'asset/img/sr대퀵.png',
          'asset/img/칙패드.png',
          'asset/img/앵글.png',
          'asset/img/수직.png',
          'asset/img/하프.png',
          'asset/img/라이트.png',
          'asset/img/엄지.png',
          'asset/img/레이저사이트.png',
        ],
        'attachments_name': [
          '레드 도트 사이트',
          '홀로그램 조준기',
          '2배율 스코프',
          '3배율 스코프',
          '4배율 스코프',
          '6배율 스코프',
          '8배율 스코프',
          '15배율 스코프',
          '캔티드 사이트',
          '4배율 열화상 스코프',
          '소음기(AR,DMR,S12K)',
          '소염기(AR,DMR,S12K)',
          '보정기(AR,DMR,S12K)',
          '소음기(SR,DMR)',
          '소염기(SR,DMR)',
          '보정기(SR,DMR)',
          '퀵드로우 탄창(AR,DMR,S12K)',
          '대용량 탄창(AR,DMR,S12K)',
          '대용량 퀵드로우 탄창(AR,DMR,S12K)',
          '대용량 탄창(SR,DMR)',
          '대용량 퀵드로우 탄창(SR,DMR)',
          '칙패드',
          '앵글 손잡이',
          '수직 손잡이',
          '하프 그립',
          '라이트 그립',
          '엄지 그립',
          '레이저 사이트'
        ],
      },
      {
        'type': 'dmr',
        'name': 'MK14',
        'ammunition': '7.62mm',
        'ammunition_image': 'asset/img/7탄.png',
        'image': 'asset/img/mk14.png',
        'magazine': '10',
        'shotmode': '단발/연사',
        'damage': '61',
        'muzzleVelocity': '853m/s',
        'stoppingPower': '20000',
        'ttk': '0.27',
        'dps': '712',
        'reloadTime': '3.683s',
        'spawnArea': '보급 무기',
        'attachments': [
          'asset/img/레드도트.png',
          'asset/img/홀로그램.png',
          'asset/img/2배율.png',
          'asset/img/3배율.png',
          'asset/img/4배율.png',
          'asset/img/6배율.png',
          'asset/img/8배율.png',
          'asset/img/15배율.png',
          'asset/img/캔티드.png',
          'asset/img/열화상4배율.png',
          'asset/img/ar소음기.png',
          'asset/img/ar소염기.png',
          'asset/img/ar보정기.png',
          'asset/img/sr소음기.png',
          'asset/img/sr소염기.png',
          'asset/img/sr보정기.png',
          'asset/img/ar퀴드로우.png',
          'asset/img/ar대탄.png',
          'asset/img/ar대퀵.png',
          'asset/img/sr대탄.png',
          'asset/img/sr대퀵.png',
          'asset/img/칙패드.png',
        ],
        'attachments_name': [
          '레드 도트 사이트',
          '홀로그램 조준기',
          '2배율 스코프',
          '3배율 스코프',
          '4배율 스코프',
          '6배율 스코프',
          '8배율 스코프',
          '15배율 스코프',
          '캔티드 사이트',
          '4배율 열화상 스코프',
          '소음기(AR,DMR,S12K)',
          '소염기(AR,DMR,S12K)',
          '보정기(AR,DMR,S12K)',
          '소음기(SR,DMR)',
          '소염기(SR,DMR)',
          '보정기(SR,DMR)',
          '퀵드로우 탄창(AR,DMR,S12K)',
          '대용량 탄창(AR,DMR,S12K)',
          '대용량 퀵드로우 탄창(AR,DMR,S12K)',
          '대용량 탄창(SR,DMR)',
          '대용량 퀵드로우 탄창(SR,DMR)',
          '칙패드',
        ],
      },
      {
        'type': 'dmr',
        'name': 'SLR',
        'ammunition': '7.62mm',
        'ammunition_image': 'asset/img/7탄.png',
        'image': 'asset/img/slr.png',
        'magazine': '10',
        'shotmode': '단발',
        'damage': '56',
        'muzzleVelocity': '840m/s',
        'stoppingPower': '20000',
        'ttk': '0.33',
        'dps': '509.1',
        'reloadTime': '3.1s',
        'spawnArea': '모든맵',
        'attachments': [
          'asset/img/레드도트.png',
          'asset/img/홀로그램.png',
          'asset/img/2배율.png',
          'asset/img/3배율.png',
          'asset/img/4배율.png',
          'asset/img/6배율.png',
          'asset/img/8배율.png',
          'asset/img/15배율.png',
          'asset/img/캔티드.png',
          'asset/img/열화상4배율.png',
          'asset/img/ar소음기.png',
          'asset/img/ar소염기.png',
          'asset/img/ar보정기.png',
          'asset/img/sr소음기.png',
          'asset/img/sr소염기.png',
          'asset/img/sr보정기.png',
          'asset/img/ar퀴드로우.png',
          'asset/img/ar대탄.png',
          'asset/img/ar대퀵.png',
          'asset/img/sr대탄.png',
          'asset/img/sr대퀵.png',
          'asset/img/칙패드.png',
        ],
        'attachments_name': [
          '레드 도트 사이트',
          '홀로그램 조준기',
          '2배율 스코프',
          '3배율 스코프',
          '4배율 스코프',
          '6배율 스코프',
          '8배율 스코프',
          '15배율 스코프',
          '캔티드 사이트',
          '4배율 열화상 스코프',
          '소음기(AR,DMR,S12K)',
          '소염기(AR,DMR,S12K)',
          '보정기(AR,DMR,S12K)',
          '소음기(SR,DMR)',
          '소염기(SR,DMR)',
          '보정기(SR,DMR)',
          '퀵드로우 탄창(AR,DMR,S12K)',
          '대용량 탄창(AR,DMR,S12K)',
          '대용량 퀵드로우 탄창(AR,DMR,S12K)',
          '대용량 탄창(SR,DMR)',
          '대용량 퀵드로우 탄창(SR,DMR)',
          '칙패드',
        ],
      },
      {
        'type': 'dmr',
        'name': '드라구노프',
        'ammunition': '7.62mm',
        'ammunition_image': 'asset/img/7탄.png',
        'image': 'asset/img/드라구노프.png',
        'magazine': '10',
        'shotmode': '단발',
        'damage': '60',
        'muzzleVelocity': '830m/s',
        'stoppingPower': '-',
        'ttk': '1.2',
        'dps': '157.5',
        'reloadTime': '3.4s',
        'spawnArea': '모든맵',
        'attachments': [
          'asset/img/레드도트.png',
          'asset/img/홀로그램.png',
          'asset/img/2배율.png',
          'asset/img/3배율.png',
          'asset/img/4배율.png',
          'asset/img/6배율.png',
          'asset/img/8배율.png',
          'asset/img/15배율.png',
          'asset/img/캔티드.png',
          'asset/img/열화상4배율.png',
          'asset/img/ar소음기.png',
          'asset/img/ar소염기.png',
          'asset/img/ar보정기.png',
          'asset/img/sr소음기.png',
          'asset/img/sr소염기.png',
          'asset/img/sr보정기.png',
          'asset/img/ar퀴드로우.png',
          'asset/img/ar대탄.png',
          'asset/img/ar대퀵.png',
          'asset/img/sr대탄.png',
          'asset/img/sr대퀵.png',
          'asset/img/칙패드.png',
        ],
        'attachments_name': [
          '레드 도트 사이트',
          '홀로그램 조준기',
          '2배율 스코프',
          '3배율 스코프',
          '4배율 스코프',
          '6배율 스코프',
          '8배율 스코프',
          '15배율 스코프',
          '캔티드 사이트',
          '4배율 열화상 스코프',
          '소음기(AR,DMR,S12K)',
          '소염기(AR,DMR,S12K)',
          '보정기(AR,DMR,S12K)',
          '소음기(SR,DMR)',
          '소염기(SR,DMR)',
          '보정기(SR,DMR)',
          '퀵드로우 탄창(AR,DMR,S12K)',
          '대용량 탄창(AR,DMR,S12K)',
          '대용량 퀵드로우 탄창(AR,DMR,S12K)',
          '대용량 탄창(SR,DMR)',
          '대용량 퀵드로우 탄창(SR,DMR)',
          '칙패드',
        ],
      },
      {
        'type': 'dmr',
        'name': 'VSS',
        'ammunition': '9mm',
        'ammunition_image': 'asset/img/9탄.png',
        'image': 'asset/img/vss.png',
        'magazine': '10',
        'shotmode': '단발/연사',
        'damage': '43',
        'muzzleVelocity': '330m/s',
        'stoppingPower': '20000',
        'ttk': '0.344',
        'dps': '504',
        'reloadTime': '3.5s',
        'spawnArea': '모든맵(카라킨 제외)',
        'attachments': [
          'asset/img/캔티드.png',
          'asset/img/ar퀴드로우.png',
          'asset/img/ar대탄.png',
          'asset/img/ar대퀵.png',
          'asset/img/sr대탄.png',
          'asset/img/sr대퀵.png',
          'asset/img/칙패드.png',
        ],
        'attachments_name': [
          '캔티드 사이트',
          '퀵드로우 탄창(AR,DMR,S12K)',
          '대용량 탄창(AR,DMR,S12K)',
          '대용량 퀵드로우 탄창(AR,DMR,S12K)',
          '대용량 탄창(SR,DMR)',
          '대용량 퀵드로우 탄창(SR,DMR)',
          '칙패드',
        ],
      },
    ];

    return SafeArea(
      child: Scaffold(
        backgroundColor: Color(0xFFF2AA00), // 배경색을 검정색으로 설정합니다.
        appBar: AppBar(
          backgroundColor: Colors.black,
          title: Text(
            'DMR - 저격 소총',
            style: textStyle,
          ),
        ),
        body: Padding(
          padding: const EdgeInsets.all(8.0), // 그리드에 패딩을 추가합니다.
          child: GridView.builder(
            gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
              crossAxisCount: 3, // 3개의 열을 가진 그리드 뷰를 생성합니다.
              childAspectRatio: 0.75, // 셀의 가로 세로 비율을 조정합니다.
            ),
            itemCount: gunList.length, // 총기의 갯수만큼 아이템을 생성합니다.
            itemBuilder: (context, index) {
              return Card(
                // 카드 위젯을 사용하여 각 항목을 감쌉니다.
                color: Colors.grey[900], // 카드 배경색을 설정합니다.
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center, // 센터 정렬을 적용합니다.
                  children: [
                    Expanded(
                      child: IconButton(
                        icon: Image.asset(
                          gunList[index]['image']!, // 이미지 경로를 사용합니다.
                          fit: BoxFit.contain, // 이미지를 비율에 맞게 조정합니다.
                        ),
                        iconSize: 200, // 아이콘의 크기를 지정합니다.
                        onPressed: () {
                          Navigator.of(context).push(
                            MaterialPageRoute(
                                builder: (_) =>
                                    GunInfoScreen(gunData: gunList[index])),
                          );
                        },
                      ),
                    ),
                    Text(
                      gunList[index]['name']!, // 총기의 이름을 표시합니다.
                      style: textStyle,
                    ),
                  ],
                ),
              );
            },
          ),
        ),
      ),
    );
  }
}
