import 'package:flutter/material.dart';

import 'gun_info.dart';

class SmgScreen extends StatelessWidget {
  const SmgScreen({super.key});

  @override
  Widget build(BuildContext context) {
    TextStyle textStyle = TextStyle(
      color: Colors.white,
      fontSize: 15.0,
      fontWeight: FontWeight.w700,
    );

    // 총기 리스트를 정의합니다.
    final List<Map<String, dynamic>> gunList = [
      {
        'type': 'smg',
        'name': 'Micro UZI',
        'ammunition': '9mm',
        'ammunition_image': 'asset/img/9탄.png',
        'image': 'asset/img/우지.png',
        'magazine': '25',
        'shotmode': '단발/연사',
        'damage': '27.3',
        'muzzleVelocity': '350m/s',
        'stoppingPower': '5000',
        'ttk': '0.336',
        'dps': '568.7',
        'reloadTime': '3.1s',
        'spawnArea': '모든맵',
        'attachments': [
          'asset/img/레드도트.png',
          'asset/img/홀로그램.png',
          'asset/img/smg소음기.png',
          'asset/img/smg소염기.png',
          'asset/img/smg보정기.png',
          'asset/img/smg퀵드로우.png',
          'asset/img/smg대탄.png',
          'asset/img/smg대퀵.png',
          'asset/img/smg개머리판.png',
        ],
        'attachments_name': [
          '레드 도트 사이트',
          '홀로그램 조준기',
          '소음기(권총,SMG)',
          '소염기(권총,SMG)',
          '보정기(권총,SMG)',
          '퀵드로우 탄창(권총,SMG)',
          '대용량 탄창(권총,SMG)',
          '대용량 퀵드로우 탄창(권총,SMG)',
          '접이식 개머리판(스콜피온,마이크로 UZI,MP9)'
        ],
      },
      {
        'type': 'smg',
        'name': 'Vector',
        'ammunition': '9mm',
        'ammunition_image': 'asset/img/9탄.png',
        'image': 'asset/img/백터.png',
        'magazine': '19',
        'shotmode': '단발/2점사/연사',
        'damage': '32.55',
        'muzzleVelocity': '380m/s',
        'stoppingPower': '7000',
        'ttk': '0.327',
        'dps': '597.2',
        'reloadTime': '2.2s',
        'spawnArea': '모든맵(비켄디, 론도 제외)',
        'attachments': [
          'asset/img/레드도트.png',
          'asset/img/홀로그램.png',
          'asset/img/smg소음기.png',
          'asset/img/smg소염기.png',
          'asset/img/smg보정기.png',
          'asset/img/smg퀵드로우.png',
          'asset/img/smg대탄.png',
          'asset/img/smg대퀵.png',
          'asset/img/개머리판.png',
          'asset/img/중량개머리판.png',
          'asset/img/수직.png',
          'asset/img/하프.png',
          'asset/img/라이트.png',
          'asset/img/레이저사이트.png',
        ],
        'attachments_name': [
          '레드 도트 사이트',
          '홀로그램 조준기',
          '소음기(권총,SMG)',
          '소염기(권총,SMG)',
          '보정기(권총,SMG)',
          '퀵드로우 탄창(권총,SMG)',
          '대용량 탄창(권총,SMG)',
          '대용량 퀵드로우 탄창(권총,SMG)',
          '전술 개머리판',
          '중량형 개머리판(SMG,AR,M249)',
          '수직 손잡이',
          '하프 그립',
          '라이트 그립',
          '레이저 사이트'
        ],
      },
      {
        'type': 'smg',
        'name': 'UMP45',
        'ammunition': '.45ACP',
        'ammunition_image': 'asset/img/45탄.png',
        'image': 'asset/img/움프.png',
        'magazine': '25',
        'shotmode': '단발/2점사/연사',
        'damage': '43.05',
        'muzzleVelocity': '360m/s',
        'stoppingPower': '7000',
        'ttk': '0.46',
        'dps': '480.7',
        'reloadTime': '3.1s',
        'spawnArea': '모든맵',
        'attachments': [
          'asset/img/레드도트.png',
          'asset/img/홀로그램.png',
          'asset/img/2배율.png',
          'asset/img/3배율.png',
          'asset/img/4배율.png',
          'asset/img/6배율.png',
          'asset/img/캔티드.png',
          'asset/img/열화상4배율.png',
          'asset/img/smg소음기.png',
          'asset/img/smg소염기.png',
          'asset/img/smg보정기.png',
          'asset/img/smg퀵드로우.png',
          'asset/img/smg대탄.png',
          'asset/img/smg대퀵.png',
          'asset/img/앵글.png',
          'asset/img/수직.png',
          'asset/img/하프.png',
          'asset/img/엄지.png',
          'asset/img/라이트.png',
          'asset/img/레이저사이트.png',
        ],
        'attachments_name': [
          '레드 도트 사이트',
          '홀로그램 조준기',
          '2배율 스코프',
          '3배율 스코프',
          '4배율 스코프',
          '6배율 스코프',
          '캔티드 사이트',
          '4배율 열화상 스코프',
          '소음기(권총,SMG)',
          '소염기(권총,SMG)',
          '보정기(권총,SMG)',
          '퀵드로우 탄창(권총,SMG)',
          '대용량 탄창(권총,SMG)',
          '대용량 퀵드로우 탄창(권총,SMG)',
          '앵글 손잡이',
          '수직 손잡이',
          '하프 그립',
          '엄지 그립',
          '라이트 그립',
          '레이저 사이트'
        ],
      },
      {
        'type': 'smg',
        'name': '토미건',
        'ammunition': '.45ACP',
        'ammunition_image': 'asset/img/45탄.png',
        'image': 'asset/img/토미건.png',
        'magazine': '30',
        'shotmode': '단발/연사',
        'damage': '42',
        'muzzleVelocity': '280m/s',
        'stoppingPower': '7000',
        'ttk': '0.43',
        'dps': '525',
        'reloadTime': '3.450s',
        'spawnArea': '모든맵',
        'attachments': [
          'asset/img/레드도트.png',
          'asset/img/홀로그램.png',
          'asset/img/smg소음기.png',
          'asset/img/smg퀵드로우.png',
          'asset/img/smg대탄.png',
          'asset/img/smg대퀵.png',
          'asset/img/수직.png',
        ],
        'attachments_name': [
          '레드 도트 사이트',
          '홀로그램 조준기',
          '소음기(권총,SMG)',
          '퀵드로우 탄창(권총,SMG)',
          '대용량 탄창(권총,SMG)',
          '대용량 퀵드로우 탄창(권총,SMG)',
          '수직 손잡이',
        ],
      },
      {
        'type': 'smg',
        'name': 'PP0-19 Bizon',
        'ammunition': '9mm',
        'ammunition_image': 'asset/img/9탄.png',
        'image': 'asset/img/비존.png',
        'magazine': '53',
        'shotmode': '단발/연사',
        'damage': '37.8',
        'muzzleVelocity': '380m/s',
        'stoppingPower': '7000',
        'ttk': '0.43',
        'dps': '440.1',
        'reloadTime': '3.8s',
        'spawnArea': '에란겔, 미라마, 비켄디, 데스턴',
        'attachments': [
          'asset/img/레드도트.png',
          'asset/img/홀로그램.png',
          'asset/img/2배율.png',
          'asset/img/3배율.png',
          'asset/img/4배율.png',
          'asset/img/6배율.png',
          'asset/img/캔티드.png',
          'asset/img/열화상4배율.png',
          'asset/img/smg소음기.png',
          'asset/img/smg소염기.png',
          'asset/img/smg보정기.png',
        ],
        'attachments_name': [
          '레드 도트 사이트',
          '홀로그램 조준기',
          '2배율 스코프',
          '3배율 스코프',
          '4배율 스코프',
          '6배율 스코프',
          '캔티드 사이트',
          '4배율 열화상 스코프',
          '소음기(권총,SMG)',
          '소염기(권총,SMG)',
          '보정기(권총,SMG)',
        ],
      },
      {
        'type': 'smg',
        'name': 'MP5K',
        'ammunition': '9mm',
        'ammunition_image': 'asset/img/9탄.png',
        'image': 'asset/img/mp5.png',
        'magazine': '30',
        'shotmode': '단발/3점사/연사',
        'damage': '34.65',
        'muzzleVelocity': '380m/s',
        'stoppingPower': '7000',
        'ttk': '0.4',
        'dps': '520.3',
        'reloadTime': '3.6s',
        'spawnArea': '비켄디, 카라킨, 헤이브, 데스턴',
        'attachments': [
          'asset/img/레드도트.png',
          'asset/img/홀로그램.png',
          'asset/img/2배율.png',
          'asset/img/3배율.png',
          'asset/img/4배율.png',
          'asset/img/6배율.png',
          'asset/img/캔티드.png',
          'asset/img/열화상4배율.png',
          'asset/img/smg소음기.png',
          'asset/img/smg소염기.png',
          'asset/img/smg보정기.png',
          'asset/img/smg퀵드로우.png',
          'asset/img/smg대탄.png',
          'asset/img/smg대퀵.png',
          'asset/img/개머리판.png',
          'asset/img/중량개머리판.png',
          'asset/img/앵글.png',
          'asset/img/수직.png',
          'asset/img/하프.png',
          'asset/img/엄지.png',
          'asset/img/라이트.png',
          'asset/img/레이저사이트.png',
        ],
        'attachments_name': [
          '레드 도트 사이트',
          '홀로그램 조준기',
          '2배율 스코프',
          '3배율 스코프',
          '4배율 스코프',
          '6배율 스코프',
          '캔티드 사이트',
          '4배율 열화상 스코프',
          '소음기(권총,SMG)',
          '소염기(권총,SMG)',
          '보정기(권총,SMG)',
          '퀵드로우 탄창(권총,SMG)',
          '대용량 탄창(권총,SMG)',
          '대용량 퀵드로우 탄창(권총,SMG)',
          '전술 개머리판',
          '중량형 개머리판(SMG,AR,M249)',
          '앵글 손잡이',
          '수직 손잡이',
          '하프 그립',
          '엄지 그립',
          '라이트 그립',
          '레이저 사이트'
        ],
      },
      {
        'type': 'smg',
        'name': 'MP9',
        'ammunition': '9mm',
        'ammunition_image': 'asset/img/9탄.png',
        'image': 'asset/img/mp9.png',
        'magazine': '30',
        'shotmode': '단발/연사',
        'damage': '32.55',
        'muzzleVelocity': '400m/s',
        'stoppingPower': '7000',
        'ttk': '-',
        'dps': '542.5',
        'reloadTime': '-',
        'spawnArea': '데스턴',
        'attachments': [
          'asset/img/레드도트.png',
          'asset/img/홀로그램.png',
          'asset/img/smg퀵드로우.png',
          'asset/img/smg대탄.png',
          'asset/img/smg대퀵.png',
          'asset/img/smg개머리판.png',
        ],
        'attachments_name': [
          '레드 도트 사이트',
          '홀로그램 조준기',
          '퀵드로우 탄창(권총,SMG)',
          '대용량 탄창(권총,SMG)',
          '대용량 퀵드로우 탄창(권총,SMG)',
          '접이식 개머리판(스콜피온,마이크로 UZI,MP9)'
        ],
      },
      {
        'type': 'smg',
        'name': 'P90',
        'ammunition': '5.7mm',
        'ammunition_image': 'asset/img/5.7탄.png',
        'image': 'asset/img/p90.png',
        'magazine': '50',
        'shotmode': '단발/연사',
        'damage': '36.75',
        'muzzleVelocity': '715/s',
        'stoppingPower': '7000',
        'ttk': '0.362',
        'dps': '612.5',
        'reloadTime': '-',
        'spawnArea': '보급 무기',
        'attachments': [
        ],
        'attachments_name': [
        ],
      },
      {
        'type': 'smg',
        'name': 'JS9',
        'ammunition': '9mm',
        'ammunition_image': 'asset/img/9탄.png',
        'image': 'asset/img/js9.png',
        'magazine': '30',
        'shotmode': '단발/연사',
        'damage': '35.7',
        'muzzleVelocity': '400m/s',
        'stoppingPower': '-',
        'ttk': '0.402',
        'dps': '535.5',
        'reloadTime': '-',
        'spawnArea': '론도',
        'attachments': [
          'asset/img/레드도트.png',
          'asset/img/홀로그램.png',
          'asset/img/2배율.png',
          'asset/img/3배율.png',
          'asset/img/4배율.png',
          'asset/img/6배율.png',
          'asset/img/캔티드.png',
          'asset/img/열화상4배율.png',
          'asset/img/smg소음기.png',
          'asset/img/smg소염기.png',
          'asset/img/smg보정기.png',
          'asset/img/smg퀵드로우.png',
          'asset/img/smg대탄.png',
          'asset/img/smg대퀵.png',

        ],
        'attachments_name': [
          '레드 도트 사이트',
          '홀로그램 조준기',
          '2배율 스코프',
          '3배율 스코프',
          '4배율 스코프',
          '6배율 스코프',
          '캔티드 사이트',
          '4배율 열화상 스코프',
          '소음기(권총,SMG)',
          '소염기(권총,SMG)',
          '보정기(권총,SMG)',
          '퀵드로우 탄창(권총,SMG)',
          '대용량 탄창(권총,SMG)',
          '대용량 퀵드로우 탄창(권총,SMG)',

        ],
      },
    ];

    return SafeArea(
      child: Scaffold(
        backgroundColor: Color(0xFFF2AA00), // 배경색을 검정색으로 설정합니다.
        appBar: AppBar(
          backgroundColor: Colors.black,
          title: Text(
            'SMG - 기관단총',
            style: textStyle,
          ),
        ),
        body: Padding(
          padding: const EdgeInsets.all(8.0), // 그리드에 패딩을 추가합니다.
          child: GridView.builder(
            gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
              crossAxisCount: 3, // 3개의 열을 가진 그리드 뷰를 생성합니다.
              childAspectRatio: 0.75, // 셀의 가로 세로 비율을 조정합니다.
            ),
            itemCount: gunList.length, // 총기의 갯수만큼 아이템을 생성합니다.
            itemBuilder: (context, index) {
              return Card(
                // 카드 위젯을 사용하여 각 항목을 감쌉니다.
                color: Colors.grey[900], // 카드 배경색을 설정합니다.
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center, // 센터 정렬을 적용합니다.
                  children: [
                    Expanded(
                      child: IconButton(
                        icon: Image.asset(
                          gunList[index]['image']!, // 이미지 경로를 사용합니다.
                          fit: BoxFit.contain, // 이미지를 비율에 맞게 조정합니다.
                        ),
                        iconSize: 200, // 아이콘의 크기를 지정합니다.
                        onPressed: () {
                          Navigator.of(context).push(
                            MaterialPageRoute(
                                builder: (_) =>
                                    GunInfoScreen(gunData: gunList[index])),
                          );
                        },
                      ),
                    ),
                    Text(
                      gunList[index]['name']!, // 총기의 이름을 표시합니다.
                      style: textStyle,
                    ),
                  ],
                ),
              );
            },
          ),
        ),
      ),
    );
  }
}
